version: '3.8'

services:
  web:
    build: .
    container_name: fliphawk-web
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://fliphawk:fliphawk@db:5432/fliphawk
      - REDIS_URL=redis://redis:6379/0
      - CACHE_REDIS_URL=redis://redis:6379/1
      - RATELIMIT_STORAGE_URL=redis://redis:6379/2
    depends_on:
      - db
      - redis
    volumes:
      - ./logs:/app/logs
      - ./static:/app/static
    networks:
      - fliphawk-network

  db:
    image: postgres:14-alpine
    container_name: fliphawk-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=fliphawk
      - POSTGRES_PASSWORD=fliphawk
      - POSTGRES_DB=fliphawk
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fliphawk-network

  redis:
    image: redis:7-alpine
    container_name: fliphawk-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - fliphawk-network

  nginx:
    image: nginx:alpine
    container_name: fliphawk-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./static:/app/static:ro
    depends_on:
      - web
    networks:
      - fliphawk-network

  prometheus:
    image: prom/prometheus:latest
    container_name: fliphawk-prometheus
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - fliphawk-network

  grafana:
    image: grafana/grafana:latest
    container_name: fliphawk-grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - fliphawk-network

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  fliphawk-network:
    driver: bridge
