# Prometheus configuration for FlipHawk monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'fliphawk-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fliphawk-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['web:5000']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alerts.yml"

# Recording rules
recording_rules:
  - record: job:fliphawk_requests_total:sum
    expr: sum(rate(http_requests_total{job="fliphawk-app"}[5m])) by (job)
  
  - record: job:fliphawk_request_duration_seconds:avg
    expr: avg(rate(http_request_duration_seconds_sum{job="fliphawk-app"}[5m])) by (job)
  
  - record: job:fliphawk_cache_hit_rate:avg
    expr: sum(rate(cache_hits_total{job="fliphawk-app"}[5m])) / sum(rate(cache_operations_total{job="fliphawk-app"}[5m]))
  
  - record: job:fliphawk_scan_duration_seconds:avg
    expr: avg(rate(scan_duration_seconds_sum{job="fliphawk-app"}[5m])) by (job)
  
  - record: job:fliphawk_opportunities_found:sum
    expr: sum(rate(opportunities_found_total{job="fliphawk-app"}[5m])) by (job)
